server:
  port: 8081

spring:
  application:
    name: user-resource
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9000}

logging:
  level:
    org.springframework.security: debug
